version: 0.0
os: linux

files:
  - source: ./dist
    destination: /var/www/pirika
    file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
  - location: scripts/appStop.sh
    timeout: 300
  BeforeInstall:
  - location: scripts/beforeInstall.sh
    timeout: 300
  ApplicationStart:
  - location: scripts/appStart.sh
    timeout: 300
  