version: 0.0
os: linux

files:
  - source: Build/*
    destination: /opt/pirika/publish
    file_exists_behavior: RETAIN
  - source: Build/*
    destination: /var/www/pirika
    file_exists_behavior: RETAIN

hooks:
  ApplicationStop:
  - location: scripts/appStop.sh
    timeout: 300
  BeforeInstall:
  - location: scripts/beforeInstall/serverInstall.sh
    timeout: 300
  - location: scripts/beforeInstall/clientInstall.sh
    timeout: 300
  ApplicationStart:
  - location: scripts/appStart.sh
    timeout: 300