Version: 0.0
os: linux

files:
  - source: frontend/dist
    destination: /var/www/pirika
    file_exists_behavior: OVERWRITE
  - source: backend/publish
    destination: /opt/backend
    file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
  - location: scripts/appStop.sh
    timeout: 300
    runas: LabRole
  BeforeInstall:
  - location: scripts/beforeInstall.sh
    timeout: 300
    runas: LabRole
  ApplicationStart:
  - location: scripts/appStart.sh
    timeout: 300
    runas: LabRole
  