version: 0.0
os: linux

files:
  - source: Server/publish
    destination: /opt/pirika/publish
    file_exists_behavior: OVERWRITE
  - source: Client/dist/*
    destination: /var/www/pirika
    file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
  - location: scripts/appStop.sh
    timeout: 300
  BeforeInstall:
  - location: scripts/beforeInstall/serverInstall.sh
    timeout: 300
  - location: scripts/beforeInstall/clientInstall.sh
    timeout: 300
  ApplicationStart:
  - location: scripts/appStart.sh
    timeout: 300